pipeline {
	agent any
	tools {
		jdk "jdk"
		maven "maven"
	}
	stages{
		stage("Build"){
			steps{
				set current_time=%time:~0,5% 
				if(%current_time% > "12:00"){

					echo "Good Afternoon Veysel. Welcome to COMP367 "
				}
				else{
					echo "Welcome to COMP367"
				}
			}
		}
	}
}
